dist: trusty
language: node_js
node_js:
- stable
before_script:
- npm install
script:
- npm test
deploy:
  provider: heroku
  app: covid-mapper
  api_key:
    secure: KKa+Dne+v86Adn9x7Fkk1P4KDMS12EuKU02t1NGdmMbzQCjyf4k9kM+rOWwqJRMbJKHnm6GGGDyafMl0F7WQnUQlc7mmD+y+V3dkul7k32vptz71o0P6ODi9x+tUJtqjlMVPERkDS8M3HHUudl0NT8mWGbmbeV/jlunzV7jE6Rid5nsYgQr2Xd+GKqqUiIeeC2ytL7ZVsheHSN6bUNh0UPhfgQ6hu4ARYPYW4qKqk5QOajbx3kdOxdIIXHU4ciN6npCBig3wR9EOUWwpKV21rAbvn+sRKvSZIFtD2I4mDH1FYgznuVNTc+x4YPmFB4fOFmOAhD7OCzZWNofN5LZC/OOe8IrPTkGG3V9jjRi1DYYBNbMCqmml6Drs1uPkNBU6I7tq4csmQuvVp/Pi0/2YFa/WveDsrUv0CXSICY7mB5l93DiPqYRaDYpPV/uedIR2cp/PuSy5OsxEGBZEHp+1CxBhFwJuoiZdPGm9T5u8n17FO+77cOkRAnlzOLgfb/L9JdyG7FltzK5gwXTdjPKeq349zHhJxtsbdDZ5AKXZAAY8+5FBYgvl4ArO4ZVR9giUpJIMpsJoB9PW/eDTbswNdf2vboU/Dt9a2a4HlwIZq3G/+fgQVrq/BVoa9lL5YAvM+caJfU/PeYqvRaQj9ZuSN6uG63psrZp2Gwkgc4CAjfI=
